export const STATIC_KEYS = {
    GLOBAL_OPT_SITE_DATA: 'GLOBAL_OPT_SITE_DATA',
    DASHBOARD_TITLES: 'DASHBOARD_TITLES',
    DASHBOARD_ALERTS: 'DASHBOARD_ALERTS',
    DASHBOARD_GLOBAL_SITE_ID: 'DASHBOARD_GLOBAL_SITE_ID',
    GLOBAL_SITE_KEY: 'GLOBAL_SITE_KEY',
    DASHBOARD_DEPLOYED_NODES: 'DASHBOARD_DEPLOYED_NODEA',
};
export const RESTRICTED_LAST_SYNC_ROUTES = ['dop/alerts', 'dop/replication', 'dop/recovery'];
