/* RIGHT SIDEBAR */
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const SHOW_RIGHT_SIDEBAR = 'SHOW_RIGHT_SIDEBAR';
export const HIDE_RIGHT_SIDEBAR = 'HIDE_RIGHT_SIDEBAR';

// Preloader
export const CHANGE_PRELOADER = 'CHANGE_PRELOADER';
export const CHANGE_SIDEBAR_TYPE = 'CHANGE_SIDEBAR_TYPE';

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_SUCCESS_PARTIAL = 'AUTHENTICATE_USER_SUCCESS_PARTIAL';
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const APP_TYPE = 'APP_TYPE';
export const APP_LICENSE_INFO = 'APP_LICENSE_INFO';
export const APP_USER = 'APP_USER';
export const APP_USER_CHANGE_PASSWORD = 'APP_USER_CHANGE_PASSWORD';

// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

// Sites
export const FETCH_SITES = 'FETCH_SITES';
export const UPDATE_SELECTED_SITES = 'UPDATE_SELECTED_SITES';

// Modal
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// INPUT HANDLING
export const VALUE_CHANGE = 'VALUE_CHANGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

// GLOBAL
export const ADD_KEY_TO_APPLICATION_LOADER = 'ADD_KEY_TO_APPLICATION_LOADER';
export const REMOVE_KEY_FROM_APPLICATION_LOADER = 'REMOVE_KEY_FROM_APPLICATION_LOADER';

// Modal
export const CLOSE_WIZARD = 'CLOSE_WIZARD';
export const OPEN_WIZARD = 'OPEN_WIZARD';
// DR palns
export const FETCH_DR_PLANS = 'FETCH_DR_PLANS';
export const FETCH_DR_PLAN_DETAILS = 'FETCH_DR_PLAN_DETAILS';
export const UPDATE_SELECTED_DR_PLAN = 'UPDATE_SELECTED_DR_PLAN';

// jobs
export const FETCH_REPLICATION_JOBS = 'FETCH_REPLICATION_JOBS';
export const FETCH_RECOVERY_JOBS = 'FETCH_RECOVERY_JOBS';
export const CHANGE_REPLICATION_JOB_TYPE = 'CHANGE_REPLICATION_JOB_TYPE';
export const CHANGE_RECOVERY_JOB_TYPE = 'CHANGE_RECOVERY_JOB_TYPE';

// dashboard
export const DASHBOARD_TILE_DATA = 'DASHBOARD_TILE_DATA';
export const DASHBOARD_REPLICATION_STAT = 'DASHBOARD_REPLICATION_STAT';
export const DASHBOARD_FETCH_DR_PLAN_DETAILS = 'DASHBOARD_FETCH_DR_PLAN_DETAILS';
export const DASHBOARD_PROTECTED_VM_STAT = 'DASHBOARD_PROTECTED_VM_STAT';
export const DASHBOARD_NODE_INFO_STAT = 'DASHBOARD_NODE_INFO_STAT';

// events
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const FILTER_EVENTS = 'FILTER_EVENTS';

// events
export const FETCH_ALERTS = 'FETCH_ALERTS';
export const SELECT_ALERT = 'SELECT_EVENT';
export const SELECTED_ALERT_EVENT = 'SELECTED_ALERT_EVENT';
export const MARK_ALERT_AS_READ = 'MARK_ALERT_AS_READ';
export const ACKNOWLEDGE_ALERT = 'ACKNOWLEDGE_ALERT';
export const FETCH_UNREAD_ALERTS = 'FETCH_UNREAD_ALERTS';
export const FILTER_ALERTS = 'FILTER_ALERTS';

// settings
export const FETCH_SUPPORT_BUNDLES = 'FETCH_SUPPORT_BUNDLES';
export const FETCH_NODES = 'FETCH_NODES';
export const SET_SELECTED_NODES = 'SET_SELECTED_NODES';
export const FETCH_EMAIL_CONFIGURATION = 'FETCH_EMAIL_CONFIGURATION';
export const FETCH_EMAIL_RECIPIENTS = 'FETCH_EMAIL_RECIPIENTS';

// reset data
export const RESET_EVENTS = 'RESET_EVENTS';
export const RESET_ALERTS = 'RESET_ALERTS';
export const RESET_JOBS = 'RESET_JOBS';
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
export const RESET_SETTINGS = 'RESET_SETTINGS';
export const RESET_REPORT = 'RESET_SETTINGS';

// report
export const SET_REPORT_CRITERIA = 'SET_REPORT_CRITERIA';
export const SET_REPORT_OBJECT = 'SET_REPORT_OBJECT';
