/* RIGHT SIDEBAR */
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const SHOW_RIGHT_SIDEBAR = 'SHOW_RIGHT_SIDEBAR';
export const HIDE_RIGHT_SIDEBAR = 'HIDE_RIGHT_SIDEBAR';

// Preloader
export const CHANGE_PRELOADER = 'CHANGE_PRELOADER';
export const CHANGE_SIDEBAR_TYPE = 'CHANGE_SIDEBAR_TYPE';

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const APP_TYPE = 'APP_TYPE';
export const APP_LICENSE_INFO = 'APP_LICENSE_INFO';

// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

// Sites
export const FETCH_SITES = 'FETCH_SITES';
export const UPDATE_SELECTED_SITES = 'UPDATE_SELECTED_SITES';

// Modal
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// INPUT HANDLING
export const VALUE_CHANGE = 'VALUE_CHANGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

// GLOBAL
export const ADD_KEY_TO_APPLICATION_LOADER = 'ADD_KEY_TO_APPLICATION_LOADER';
export const REMOVE_KEY_FROM_APPLICATION_LOADER = 'REMOVE_KEY_FROM_APPLICATION_LOADER';

// Modal
export const CLOSE_WIZARD = 'CLOSE_WIZARD';
export const OPEN_WIZARD = 'OPEN_WIZARD';
// DR palns
export const FETCH_DR_PALNS = 'FETCH_DR_PALNS';
export const FETCH_DR_PALN_DETAILS = 'FETCH_DR_PALN_DETAILS';
export const UPDATE_SELECTED_DR_PLAN = 'UPDATE_SELECTED_DR_PLAN';

// jobs
export const FETCH_REPLICATION_JOBS = 'FETCH_REPLICATION_JOBS';
export const FETCH_RECOVERY_JOBS = 'FETCH_RECOVERY_JOBS';
export const CHANGE_REPLICATION_JOB_TYPE = 'CHANGE_REPLICATION_JOB_TYPE';
export const CHANGE_RECOVERY_JOB_TYPE = 'CHANGE_RECOVERY_JOB_TYPE';

// dashboard
export const DASHBOARD_TILE_DATA = 'DASHBOARD_TILE_DATA';
export const DASHBOARD_STAT_DATA = 'DASHBOARD_STAT_DATA';
