export const REVERSE_CONFIG_STEP = {
  ID: 'drplan.id',
  REMOTEPPLAN_ID: 'ui.edit.plan.remoteProtectionPlanId',
  NAME: 'drplan.name',
  BOOTDELAY: 'drplan.bootDelay',
  PRE_SCRIPT: 'drplan.preScript',
  POST_SCRIPT: 'drplan.postScript',
  PREE_INPUT: 'drplan.preInputs',
  POST_INPUT: 'drplan.postInputs',
  PROTECTED_SITE: 'drplan.protectedSite',
  RECOVERY_SITE: 'drplan.recoverySite',
  REPLICATION_INTERVAL: 'drplan.replicationInterval',
  SCRIPT_TIMEOUT: 'drplan.scriptTimeout',
  PROTECTED_ENTITIES_ID: 'ui.edit.plan.protectedEntities.id',
  RECOVERY_ENTITIES_ID: 'ui.edit.plan.recoveryEntities.id',
  STATUS: 'ui.edit.plan.status',
  PLAN_ID: 'ui.edit.plan.id',
  START_TIME: 'drplan.startTime',
  IS_ENCRYPTION: 'drplan.isEncryptionOnWire',
  IS_ENCRYPTION_REST: 'drplan.isEncryptionOnRest',
  PLAN_COMPRESSION: 'drplan.isCompression',
  IS_DEDUPE: 'drplan.isDeDupe',
  ENABLE_REVERSE: 'drplan.enableReverse',
  REPLICATION_POST_SCRIPT: 'drplan.replPostScript',
  REPLICATION_PRE_SCRIPT: 'drplan.replPreScript',

};
