import { APP_TYPE, RECOVERY_CHECKPOINT_TYPE, RECOVERY_JOB_TYPE, REPLICATION_JOB_TYPE } from './InputConstants';

const INITIAL_STATE = {
  global: {
    loaderKeys: {},
  },
  messages: {},
  user: { id: 1,
    context: { refresh: 0, updateID: 0 },
    passwordChangeReq: false,
    allowCancel: false,
    passwordResetReq: false,
    allowReset: false,
    isAuthenticated: false,
    token: '',
    userName: '',
    isSystemDefault: false,
    isValidating: false,
    values: {},
    errors: {},
    appType: APP_TYPE.CLIENT,
    platformType: '',
    localVMIP: '',
    privileges: [],
    license: { applicationKey: '', version: '-' },
    tree: { treeKey: '' },
    roles: [],
    users: [],
    // Added tab in redux
    drPlanDetailActiveTab: '1',
  },
  sites: { sites: [], selectedSites: [] },
  drPlans: { plans: [], selectedPlans: [], recoveryPlan: {}, allVmRecovered: false, cleanup: { selectedResources: {}, data: [] } },
  drPlaybooks: { templates: [], selectedPlaybook: {}, playbook: {} },
  modal: [],
  wizard: { steps: [], show: false, options: { title: '' } },
  jobs: { replication: [], diskReplication: [], recovery: [], replicationType: REPLICATION_JOB_TYPE.PLAN, recoveryType: RECOVERY_JOB_TYPE.PLAN, checkpointJobs: [], recoveryCheckpoints: {}, selectedCheckpoints: {}, vmCheckpoint: [], checkpointType: RECOVERY_CHECKPOINT_TYPE.PLAN, checkpointCount: 0 },
  dashboard: {
    titles: {},
    replicationStats: { completed: 0, running: 0, failures: 0, copies: 0, changeRate: 0, dataReduction: 0, rpo: 0, inSync: 0, notInsync: 0, changedRate: 0 },
    recoveryStats: { testExecutions: 0, fullRecovery: 0, migrations: 0, rto: 0 },
    protectedVMStats: { protectedVMs: 0, unprotectedVMs: 0 },
    nodes: [],
  },
  events: { data: [], selected: {}, filteredData: [] },
  alerts: { data: [], selected: {}, associatedEvent: {}, unread: [], filteredData: [] },
  settings: { bundles: [], nodes: [], selectedNodes: [], emailConfig: null, emailRecipients: [], licenses: [], replNodes: [], selectedUsers: [], idp: {} },
  reports: { criteria: {}, result: {} },
};

export default INITIAL_STATE;
