export const MODAL_CONFIGURE_NEW_SITE = 'MODAL_CONFIGURE_NEW_SITE';
export const MODAL_CONFIRMATION_WARNING = 'MODAL_CONFIRMATION_WARNINGp';
export const MODAL_ABOUT = 'MODAL_ABOUT';
export const MODAL_ALERT_DETAILS = 'MODAL_ALERT_DETAILS';
export const MODAL_GENERATE_SUPPORT_BUNDLE = 'MODAL_GENERATE_SUPPORT_BUNDLE';
