export const STACK_COMPONENT_NETWORK = 'STACK_COMPONENT_NETWORK';
export const STACK_COMPONENT_TAGS = 'STACK_COMPONENT_TAGS';
export const STACK_COMPONENT_CONFIGURATION = 'STACK_COMPONENT_CONFIGURATION';
export const STACK_COMPONENT_SECURITY_GROUP = 'STACK_COMPONENT_SECURITY_GROUP';
export const STACK_COMPONENT_LOCATION = 'STACK_COMPONENT_LOCATION';
export const STACK_COMPONENT_MEMORY = 'STACK_COMPONENT_MEMORY';
