export const STACK_COMPONENT_NETWORK = 'STACK_COMPONENT_NETWORK';
export const STACK_COMPONENT_TAGS = 'STACK_COMPONENT_TAGS';
export const STACK_COMPONENT_SECURITY_GROUP = 'STACK_COMPONENT_SECURITY_GROUP';
