export const APPLICATION_API_TOKEN = 'APPLICATION_API_TOKEN';
export const APPLICATION_API_USER = 'APPLICATION_API_USER';
export const APPLICATION_GETTING_STARTED_COMPLETED = 'APPLICATION_GETTING_STARTED_COMPLETED';
