export const APPLICATION_API_TOKEN = 'APPLICATION_API_TOKEN';
export const APPLICATION_API_USER = 'APPLICATION_API_USER';
export const APPLICATION_API_USER_ID = 'APPLICATION_API_USER_ID';
export const APPLICATION_GETTING_STARTED_COMPLETED = 'APPLICATION_GETTING_STARTED_COMPLETED';
export const API_MAX_RECORD_LIMIT = 2000;
export const APP_SET_TIMEOUT = 20;
export const DATA_GRID_SHORT_TEXT_LENGTH = 30;
