/* RIGHT SIDEBAR */
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const SHOW_RIGHT_SIDEBAR = 'SHOW_RIGHT_SIDEBAR';
export const HIDE_RIGHT_SIDEBAR = 'HIDE_RIGHT_SIDEBAR';

// Preloader
export const CHANGE_PRELOADER = 'CHANGE_PRELOADER';
export const CHANGE_SIDEBAR_TYPE = 'CHANGE_SIDEBAR_TYPE';

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_SUCCESS_PARTIAL = 'AUTHENTICATE_USER_SUCCESS_PARTIAL';
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const APP_TYPE = 'APP_TYPE';
export const APP_LICENSE_INFO = 'APP_LICENSE_INFO';
export const APP_USER = 'APP_USER';
export const APP_USER_CHANGE_PASSWORD = 'APP_USER_CHANGE_PASSWORD';
export const APP_USER_PRIVILEGES = 'APP_USER_PRIVILEGES';
export const APP_USERS = 'APP_USERS';
export const APP_REFRESH = 'APP_REFRESH';
export const TREE_DATA = 'TREE_DATA';
export const UPDATE_VALUES = 'UPDATE_VALUES';
export const DM_FORCE_UPDATE = 'DM_FORCE_UPDATE';
export const APP_USER_RESET_PASSWORD = 'APP_USER_RESET_PASSWORD';

// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

// Modal
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// INPUT HANDLING
export const VALUE_CHANGE = 'VALUE_CHANGE';
export const VALUE_CHANGES = 'VALUE_CHANGES';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

// GLOBAL
export const ADD_KEY_TO_APPLICATION_LOADER = 'ADD_KEY_TO_APPLICATION_LOADER';
export const REMOVE_KEY_FROM_APPLICATION_LOADER = 'REMOVE_KEY_FROM_APPLICATION_LOADER';

export const SET_SELECTED_USERS = 'SET_SELECTED_USERS';
export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_USERS = 'FETCH_USERS';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';

// Upgrade
export const SET_UPGRADE_STEPS = 'SET_UPGRADE_STEP';
export const SET_CURRENT_UPGRADE_STEP = 'SET_CURRENT_UPGRADE_STEP';
export const UPDATE_UPGRADE_STEPS_DATA = 'UPDATE_UPGRADE_STEPS_DATA';
export const SET_UPGRADE_SUMMARY_ACTIVE_TAB = 'SET_UPGRADE_SUMMARY_ACTIVE_TAB';
