

export const STATUS_ITEM_RENDERER = 'STATUS_ITEM_RENDERER';
export const OS_TYPE_ITEM_RENDERER = 'OS_TYPE_ITEM_RENDERER';
export const SITE_LOCATION_ITEM_RENDERER = 'SITE_LOCATION_ITEM_RENDERER';
export const NODE_NAME_ITEM_RENDERER = 'NODE_NAME_ITEM_RENDERER';
export const SERVER_PORT_ITEM_RENDERER = 'SERVER_PORT_ITEM_RENDERER';

// show time taken by any job
export const VM_BOOT_ORDER_ITEM_RENDER = 'TIME_RENDERER';
export const UPGRADE_NODE_STATUS_TABLE_STATUS_RENDERER = 'UPGRADE_NODE_STATUS_TABLE_STATUS_RENDERER';
export const LINK_RENDERER = 'LINK_RENDERER';
export const PLAN_REPLICATION_RENDERER = 'PLAN_REPLICATION_RENDERER';
export const PLAN_ALERT_RENDERER = 'PLAN_ALERT_RENDERER';
export const ALERT_ACTION_RENDERER = 'ALERT_ACTION_RENDERER';
export const STEP_STATUS_RENDERER = 'STEP_STATUS_RENDERER';
export const RECOVERY_STATUS_RENDERER = 'RECOVERY_STATUS_RENDERER';
export const COUNT_ITEM_RENDERER = 'COUNT_ITEM_RENDERER';
export const TEST_RECOVERY_TIME_ITEM_RENDERER = 'TEST_RECOVERY_TIME_ITEM_RENDERER';
export const CLEANUP_ITEM_RENDERER = 'CLEANUP_ITEM_RENDERER';
export const SITE_LINK_RENDERER = 'SITE_LINK_RENDERER';
export const PROTECTION_PLAN_NAME_RENDERER = 'PROTECTION_PLAN_NAME_RENDERER';
export const STORAGE_ITEM_RENDERER = 'STORAGE_ITEM_RENDERER';
export const TIME_DURATION_RENDERER = 'TIME_DURATION_RENDERER';
export const DATE_ITEM_RENDERER = 'DATE_ITEM_RENDERER';
export const SSH_RDP_ITEM_RENDERER = 'SSH_RDP_ITEM_RENDERER';
export const RECOVERY_TYPE_ITEM_RENDERER = 'RECOVERY_TYPE_ITEM_RENDERER';
export const DR_RECOVERY_RENDERER = 'DR_RECOVERY_RENDERER';
export const ALERTS_SEVERITY_ITEM_RENDERER = 'ALERTS_SEVERITY_ITEM_RENDERER';
export const ALERTS_TITLE_ITEM_RENDERER = 'ALERTS_TITLE_ITEM_RENDERER';
export const VM_SIZE_ITEM_RENDERER = 'VM_SIZE_ITEM_RENDERER';
export const LICENSE_USAGE_ITEM_RENDERER = 'LICENSE_USAGE_ITEM_RENDERER';
export const LICENSE_STATUS_ITEM_RENDERER = 'LICENSE_STATUS_ITEM_RENDERER';
export const ALERT_COLUMN_ITEM_RENDERER = 'ALERT_COLUMN_ITEM_RENDERER';
export const ALERT_ACK_ITEM_RENDERER = 'ALERT_ACK_ITEM_RENDERER'
export const NODE_HEALTH_COLUMN_RENDERER = 'NODE_HEALTH_COLUMN_RENDERER'
export const SIZE_ITEM_RENDERER = 'SIZE_ITEM_RENDERER'
export const SUPPORT_BUNDLE_ACTION_ITEM_RENDERER = 'SUPPORT_BUNDLE_ACTION_ITEM_RENDERER'
export const PLAN_DR_READY_RENDERER = 'PLAN_DR_READY_RENDERER'